name: Deploy container
on:
  push:
    branches: main
    paths:
      - 'Dockerfile'
      - 'install_driver.sh'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    strategy:
      matrix:
        os_version: ["20.04", "22.04"]
        driver_version: ["21.30", "22.20"]
        exclude:
          - os_version: 22.04
            driver_version: 21.30
    name: Deploy container
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and tag image
        run: docker build -f Dockerfile --build-arg UBUNTU_VERSION=${{ matrix.os_version }} --build-arg DRIVER_VERSION=${{ matrix.driver_version }} -t compscidr/amdgpu:ubuntu-${{ matrix.os_version }}-${{ matrix.driver_version }} .
      - name: tag and push
        run: |
          docker push compscidr/amdgpu:ubuntu-${{ matrix.os_version }}-${{ matrix.driver_version }}
          docker tag compscidr/amdgpu:ubuntu-${{ matrix.os_version }}-${{ matrix.driver_version }} compscidr/amdgpu:latest
          docker push compscidr/amdgpu:latest
      - name: Logout of Docker Hub
        run: docker logout
