name: Deploy container
on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy container
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build image
        run: docker build -f Dockerfile -t amdgpu:${{ github.sha }} .
      - name: tag and push
        run: |
          docker tag amdgpu:${{ github.sha }} compscidr/amdgpu:${{ github.event.release.tag_name }}
          docker push compscidr/amdgpu:${{ github.event.release.tag_name }}
          docker tag amdgpu:${{ github.sha }} compscidr/amdgpu:latest
          docker push compscidr/amdgpu:latest
      - name: Logout of Docker Hub
        run: docker logout
